env: &env
  BASE_URL: http://restaurant-drone-bucket.s3-website-us-east-1.amazonaws.com
  AWS_SESSION_TOKEN:
    from_secret: aws_session_token
  AWS_ACCESS_KEY_ID:
    from_secret: aws_access_key_id
  AWS_SECRET_ACCESS_KEY:
    from_secret: aws_secret_access_key

kind: pipeline
name: hugo-website
steps:
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      <<: *env
    commands:
      - hugo --baseURL $BASE_URL
      - ls public
    when:
      event: push
      branch: master
  - name: archive-release
    image: amazon/aws-cli
    environment:
      <<: *env
    commands:
      - export AWS_DEFAULT_REGION="us-east-1"
      - export ARCHIVE_NAME="hugo-build-${BUILD_TIMESTAMP}.tar.gz"
      - export BUILD_TIMESTAMP=$(date +%Y%m%d-%H%M%S)
      - tar -czf $ARCHIVE_NAME public/
      - echo $ARCHIVE_NAME
      - aws s3 cp $ARCHIVE_NAME s3://restaurant-drone-releases-bucket/releases/
    when:
      event: tag
      branch: master
  - name: publish-website-s3
    image: amazon/aws-cli
    environment:
      <<: *env
    commands:
      - export AWS_DEFAULT_REGION="us-east-1"
      - aws s3 sync public/ s3://restaurant-drone-bucket/ --delete --acl public-read --exclude ".DS_Store"
    when:
      event: promote
      branch: master